(if (not (boundp 'volume-change-frequency))
    (set 'volume-change-frequency "5"))
(defun volume-control (sign)
  (interactive)
  (shell-command (concat "amixer set Master " volume-change-frequency sign)))
(defun volume-plus ()
  (interactive)
  (volume-control "+"))
(defun volume-less ()
  (interactive)
  (volume-control "-"))
(global-set-key (kbd "C-c <kp-add>") 'volume-plus)
(global-set-key (kbd "C-c <kp-subtract>") 'volume-less)
